#
#
#
#
#
#
#
#
#
#
#
# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias code='code-oss --ozone-platform=wayland'
PS1='[\u@\h \W]\$ '
export PATH="$HOME/.local/npm-glob/bin:$HOME/.cargo/bin:$PATH"
eval "$(starship init bash)"
